# Generated by Django 4.2.5 on 2023-09-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('school_class', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
